[workspace]
members = []

[package]
name = "compact-pascal"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
description = "Embeddable Pascal-to-WASM compiler"
authors = ["Jon Mayo"]
license = "CC0-1.0"

[lib]
path = "src/rust/lib.rs"

[[example]]
name = "hello"
path = "examples/rust/hello/main.rs"

[dependencies]
wasmi = "1.0"
thiserror = "1.0"

[profile.release]
opt-level = 3
lto = true
